version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: "user"
      ME_CONFIG_BASICAUTH_PASSWORD: "user"
    depends_on:
      - mongodb

  mongo-seed:
    image: mongo
    restart: no
    depends_on:
      - mongodb
    volumes:
      - ./seed-data:/seed
    entrypoint: >
      bash -c "
        sleep 20 &&
        mongoimport --host mongodb --db eventmanagement --collection events --file /seed/events.json &&
        mongoimport --host mongodb --db eventmanagement --collection users --file /seed/users.json &&
        mongoimport --host mongodb --db eventmanagement --collection eventTypes --file /seed/eventTypes.json &&
        mongoimport --host mongodb --db eventmanagement --collection eventUsers --file /seed/eventUsers.json &&
        mongoimport --host mongodb --db eventmanagement --collection invitationCodes --file /seed/invitationCodes.json &&
        mongoimport --host mongodb --db eventmanagement --collection notifications --file /seed/notifications.json
      "

  backend:
    build:
      context: ./eventmanagement
    ports:
      - "8077:8077"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/eventmanagement
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/app    # Mount source code for live reload
      - /app/node_modules       # Prevent overwrite of node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # (optional) fixes file watching in Docker on some OS
    depends_on:
      - backend



volumes:
  mongo-data:
