version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: "user"
      ME_CONFIG_BASICAUTH_PASSWORD: "user"
    depends_on:
      - mongodb

  backend:
    build:
      context: ./eventmanagement
    ports:
      - "8077:8077"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/eventmanagement
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
